[package]
name = "data_collect"
version = "0.1.0"
edition = "2024"

[dependencies]
argparse = "0.2.2"
chrono = "0.4.41"
csv = "1.3.1"
glob = "0.3.2"
log = "0.4.27"
log4rs = "1.3.0"
minidom = "0.16.0"
polars = "0.48.1"
serde = "1.0.219"
